import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Next Africa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${montserrat.className} lg:px-[10rem] md:px-5 px-0 py-5  relative`}>
        <Navbar />
        {children}</body>
    </html>
  );
}
