import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Next Africa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}    relative`}>
        <div className="xl:px-[10rem] lg:px-[5rem] md:px-[2rem] px-0">
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
